import { useState } from 'react';
import { 
  CheckCircle, 
  AlertTriangle, 
  AlertCircle, 
  XCircle,
  Download,
  Save,
  Trash2,
  ChevronDown,
  ChevronUp,
  Shield
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Separator } from '@/components/ui/separator';
import { 
  Collapsible, 
  CollapsibleContent, 
  CollapsibleTrigger 
} from '@/components/ui/collapsible';
import { 
  AnalysisResult, 
  RadiologyFinding,
  ScanType,
  getScanTypeLabel,
  getSeverityColor
} from '@/lib/radiologyClient';

interface RadiologyResultsProps {
  result: AnalysisResult;
  scanType: ScanType;
  fileName: string;
  imagePreview?: string;
  onSave?: () => void;
  onDiscard?: () => void;
  isSaving?: boolean;
}

function SeverityIcon({ severity }: { severity: string }) {
  switch (severity) {
    case 'normal':
      return <CheckCircle className="h-5 w-5 text-green-600" />;
    case 'mild':
      return <AlertCircle className="h-5 w-5 text-yellow-600" />;
    case 'moderate':
      return <AlertTriangle className="h-5 w-5 text-orange-600" />;
    case 'severe':
      return <XCircle className="h-5 w-5 text-red-600" />;
    default:
      return <AlertCircle className="h-5 w-5 text-gray-600" />;
  }
}

function FindingCard({ finding, index }: { finding: RadiologyFinding; index: number }) {
  const [isOpen, setIsOpen] = useState(index === 0);

  return (
    <Collapsible open={isOpen} onOpenChange={setIsOpen}>
      <Card className={`border ${getSeverityColor(finding.severity)}`}>
        <CollapsibleTrigger asChild>
          <CardHeader className="cursor-pointer hover:bg-gray-50 transition-colors py-3">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-3">
                <SeverityIcon severity={finding.severity} />
                <div>
                  <CardTitle className="text-base">{finding.category}</CardTitle>
                  <CardDescription className="text-xs">
                    Confidence: {Math.round(finding.confidence * 100)}%
                  </CardDescription>
                </div>
              </div>
              <div className="flex items-center gap-2">
                <Badge variant="outline" className={getSeverityColor(finding.severity)}>
                  {finding.severity.charAt(0).toUpperCase() + finding.severity.slice(1)}
                </Badge>
                {isOpen ? <ChevronUp className="h-4 w-4" /> : <ChevronDown className="h-4 w-4" />}
              </div>
            </div>
          </CardHeader>
        </CollapsibleTrigger>
        <CollapsibleContent>
          <CardContent className="pt-0">
            <p className="text-sm text-gray-700">{finding.description}</p>
          </CardContent>
        </CollapsibleContent>
      </Card>
    </Collapsible>
  );
}

export function RadiologyResults({
  result,
  scanType,
  fileName,
  imagePreview,
  onSave,
  onDiscard,
  isSaving
}: RadiologyResultsProps) {
  const overallConfidence = Math.round(result.confidenceScore * 100);
  
  // Determine overall severity based on findings
  const severities = result.findings.map(f => f.severity);
  const hasSevere = severities.includes('severe');
  const hasModerate = severities.includes('moderate');
  const hasMild = severities.includes('mild');
  
  let overallStatus = 'normal';
  if (hasSevere) overallStatus = 'severe';
  else if (hasModerate) overallStatus = 'moderate';
  else if (hasMild) overallStatus = 'mild';

  const handleDownloadReport = () => {
    const report = `
RADIOLOGY AI ANALYSIS REPORT
============================
Date: ${new Date().toLocaleString()}
Scan Type: ${getScanTypeLabel(scanType)}
File: ${fileName}
AI Provider: ${result.provider}

SUMMARY
-------
${result.summary}

FINDINGS
--------
${result.findings.map((f, i) => `
${i + 1}. ${f.category}
   Severity: ${f.severity}
   Confidence: ${Math.round(f.confidence * 100)}%
   ${f.description}
`).join('\n')}

Overall Confidence: ${overallConfidence}%

DISCLAIMER
----------
${result.disclaimer}

============================
Generated by BloodVista AI
    `.trim();

    const blob = new Blob([report], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `radiology-report-${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <Card>
        <CardHeader>
          <div className="flex items-center justify-between">
            <div>
              <CardTitle className="flex items-center gap-2">
                <Shield className="h-5 w-5 text-medical-600" />
                Analysis Complete
              </CardTitle>
              <CardDescription>
                {getScanTypeLabel(scanType)} • {fileName}
              </CardDescription>
            </div>
            <div className="text-right">
              <div className="text-2xl font-bold text-medical-600">{overallConfidence}%</div>
              <div className="text-sm text-gray-500">Confidence</div>
            </div>
          </div>
        </CardHeader>
      </Card>

      {/* Image Preview (if available) */}
      {imagePreview && (
        <Card>
          <CardContent className="p-4">
            <img 
              src={imagePreview} 
              alt="Analyzed scan" 
              className="w-full h-48 object-contain bg-black rounded-lg"
            />
          </CardContent>
        </Card>
      )}

      {/* Summary */}
      <Card>
        <CardHeader>
          <CardTitle className="text-base">Summary</CardTitle>
        </CardHeader>
        <CardContent>
          <p className="text-gray-700">{result.summary}</p>
          
          <div className="mt-4 flex items-center gap-2">
            <span className="text-sm text-gray-500">Overall Assessment:</span>
            <Badge className={getSeverityColor(overallStatus)}>
              <SeverityIcon severity={overallStatus} />
              <span className="ml-1">
                {overallStatus.charAt(0).toUpperCase() + overallStatus.slice(1)}
              </span>
            </Badge>
          </div>
        </CardContent>
      </Card>

      {/* Findings */}
      <div className="space-y-3">
        <h3 className="text-lg font-semibold text-gray-900">
          Detailed Findings ({result.findings.length})
        </h3>
        {result.findings.length > 0 ? (
          result.findings.map((finding, index) => (
            <FindingCard key={index} finding={finding} index={index} />
          ))
        ) : (
          <Card>
            <CardContent className="py-8 text-center">
              <CheckCircle className="h-12 w-12 text-green-500 mx-auto mb-2" />
              <p className="text-gray-600">No significant findings detected</p>
            </CardContent>
          </Card>
        )}
      </div>

      {/* Disclaimer */}
      <Card className="border-amber-200 bg-amber-50">
        <CardContent className="py-4">
          <div className="flex gap-3">
            <AlertTriangle className="h-5 w-5 text-amber-600 flex-shrink-0 mt-0.5" />
            <p className="text-sm text-amber-800">{result.disclaimer}</p>
          </div>
        </CardContent>
      </Card>

      <Separator />

      {/* Actions */}
      <div className="flex flex-wrap gap-3">
        {onSave && (
          <Button 
            onClick={onSave} 
            disabled={isSaving}
            className="bg-medical-600 hover:bg-medical-700"
          >
            {isSaving ? (
              <>
                <div className="animate-spin rounded-full h-4 w-4 border-2 border-white border-t-transparent mr-2" />
                Saving...
              </>
            ) : (
              <>
                <Save className="h-4 w-4 mr-2" />
                Save to History
              </>
            )}
          </Button>
        )}
        
        <Button variant="outline" onClick={handleDownloadReport}>
          <Download className="h-4 w-4 mr-2" />
          Download Report
        </Button>
        
        {onDiscard && (
          <Button variant="ghost" onClick={onDiscard} className="text-red-600 hover:text-red-700">
            <Trash2 className="h-4 w-4 mr-2" />
            Discard
          </Button>
        )}
      </div>

      {/* Provider Info */}
      <p className="text-xs text-gray-400 text-center">
        Analysis powered by {result.provider.toUpperCase()} AI
      </p>
    </div>
  );
}
